version: '3.7'
services:
  api-gateway:
    build: ./api-gateway
    ports: 
      - "3000:3000"
    volumes:
      - ./api-gateway:/api-gateway
      - /api-gateway/node_modules
  # rabbitmq-server:
  #   build: ./rabbitmq-server
            

