version: '3.7'
services:
  api-gateway:
    build: ./api-gateway
    ports: 
      - "5000:5000"
    volumes:
      - ./api-gateway:/code
  # rabbitmq-server:
  #   build: ./rabbitmq-server
            

